---
title: "NES-LTER fish diet EML assembly notebook"
output: html_notebook
author: "Joe Futrelle, Stace Beaulieu"
date: "February 2022"
---

```{r}
library(ediutilities) # remotes::install_github("WHOIGit/ediutilities")
library(glue)
library(here)
library(readr)
library(httr)
library(dplyr)
library(EMLassemblyline) # remotes::install_github("EDIorg/EMLassemblyline")
```

```{r}
count_table_name <- 'Concat_Count_EDI'
meas_table_name <- 'Concat_Meas_EDI'
```

Produce assembly line templates from Excel template


```{r}
excel_template <- 'LTER_ForageFish_Info.xlsx'

sheet_to_tsv(excel_template, 'ColumnHeaders',
             glue('attributes_{count_table_name}.txt'))

sheet_to_tsv(excel_template, 'ColumnHeaders',
             glue('attributes_{meas_table_name}.txt'))

sheet_to_tsv(excel_template, 'CategoricalVariables',
             glue('catvars_{count_table_name}.txt'))

sheet_to_tsv(excel_template, 'CategoricalVariables',
             glue('catvars_{meas_table_name}.txt'))

sheet_to_tsv(excel_template, 'Personnel', 'personnel.txt')
```
Use templates in "template core metadata" step from EML assembly line

```{r}
EMLassemblyline::template_core_metadata(path=here(), license='CCBY')
```
Read in the new data and adjust to metadata templates

```{r}
count_table <- read_csv(here(glue('ForageFish_EDI/{count_table_name}.csv')))
meas_table <- read_csv(here(glue('ForageFish_EDI/{meas_table_name}.csv')))

# drop row index column from each table
count_table <- count_table[,-1]
meas_table <- meas_table[,-1]

# fix "MA" typo in meas_table
meas_table$preyCount <- as.numeric(dplyr::na_if(meas_table$preyCount, "MA"))

# cruise is not numeric
count_table$cruise <- as.factor(as.character(count_table$cruise))
meas_table$cruise <- as.factor(as.character(meas_table$cruise))
```

Read in previous version fish diet package and exclude/add columns as step towards row bind to new data
Note that version 2.2 only had one table corresponding to Concat_Count

```{r}
url <- ('https://pasta.lternet.edu/package/data/eml/knb-lter-nes/2/2/ae192ab77a510ee7b8f155770a0a157b')
httr::GET(url, write_disk(tf <- tempfile(fileext = ".csv")))

fish_diet_2013 <- read_csv(tf, TRUE, show_col_types = FALSE) 

# exclude columns no longer being used in new version of Concat_Count data table
fish_diet_2013 <- select(fish_diet_2013, -cruise_station, -decimalLongitude_flag, -time_local, -region,
                         -uniqueIdentifierFish, -scientificName_fish, -scientificNameID_fish,
                         -vernacularName)

# need to combine previous columns date and time_UTC into single column BEGIN_GMT_TOWDATE
fish_diet_2013$BEGIN_GMT_TOWDATE <- as.POSIXct(paste(fish_diet_2013$date, fish_diet_2013$time_UTC),
                                               format='%Y-%m-%d %H:%M:%S', tz='UTC')
# remove the now-unneeded date and time_UTC columns
fish_diet_2013$date <- NULL
fish_diet_2013$time_UTC <- NULL


# need to transform previous column abbrevName_fish to new column FishSpecies
# these should be categorical variables
# since the new version removes scientificName_fish, scientificNameID_fish, and vernacularName, refer to LOOKUP table in previous GitHub repo
# https://github.com/WHOIGit/nes-lter-fish-diet-isotope/blob/c64f49716e13b0e543be1b61066e0023dc7748b8/fish-lookup.csv

abbrev_lookup <- read.csv(here('fish-lookup.csv'))

fish_diet_2013$FishSpecies <- plyr::mapvalues(fish_diet_2013$abbrevName_fish,
                                              abbrev_lookup$abbrevName_fish,
                                              abbrev_lookup$FishSpecies)
# remove the now-unneeded abbrevName_fish column
fish_diet_2013$abbrevName_fish <- NULL


# What used to be a single column preyTaxon in previous package is now represented by 3 columns
# preyTaxon, preyTaxa, and preySpp matched to a 4th column Llopiz_taxa in Concat_Count data table
# thus fill preyTaxa, preySpp, and Llopiz_taxa with NA
fish_diet_2013$preyTaxa <- NA_character_
fish_diet_2013$preySpp <- NA_character_
fish_diet_2013$Llopiz_taxa <- NA_character_


# note new data for scientificNameID_preyTaxon is missing the LSID prefix

# add additional columns that are in new Concat_Count data table but not in previous version
# these may be either not applicable (e.g., Ocularunits) or not available (e.g., scientificName_Rank)
fish_diet_2013$preyNum <- NA_integer_
fish_diet_2013$Ocularunits <- NA_integer_
fish_diet_2013$Mag <- NA_integer_
fish_diet_2013$prey_mm <- NA_integer_
fish_diet_2013$Scope <- NA_character_
fish_diet_2013$gutCount <- NA_integer_
fish_diet_2013$Comments_prey <- NA_character_
fish_diet_2013$Comments_gut <- NA_character_
fish_diet_2013$scientificName_Rank <- NA_character_

```
```{r}
# add 2013 data to the count_table

count_table <- rbind(fish_diet_2013, count_table)[names(count_table)]

```

```{r}
# display data locations on a map
map_locs(count_table, xvar='decimalLongitude', yvar='decimalLatitude')
```

```{r}
# write compiled / corrected tables to project directory for consumption
# by make_eml
write_csv(count_table, here(glue('{count_table_name}.csv')), quote="needed")
write_csv(meas_table, here(glue('{meas_table_name}.csv')), quote="needed")
```

```{r}
# compute temporal coverage
temp_coverage <- temporal_coverage(append(count_table$BEGIN_GMT_TOWDATE,
                                          meas_table$BEGIN_GMT_TOWDATE))

# geographic coverage computed in EML assembly step because computing it here
# and attempting to pass it into make_eml resulted in an error message from
# make_eml
```

Produce EML

```{r}
pkg_id <- "knb-lter-nes.2.3"

dataset_title = 'Diet composition for small pelagic fishes across the Northeast U.S. Continental Shelf for NES-LTER, ongoing since 2013'

make_eml(path=here(),
         #data.path=here('ForageFish_EDI'),
         dataset.title=dataset_title,
         data.table=c(glue('{count_table_name}.csv'),
                      glue('{meas_table_name}.csv')),
         data.table.description=c('Counts of prey in individual fish guts',
                                  'Measurements of prey in individual fish guts'),
         data.table.name = c('Prey Counts',
                             'Prey Measurements'),
         data.table.quote.character = c('"', '"'),
         temporal.coverage = temp_coverage,
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(
            append(count_table$decimalLatitude, meas_table$decimalLatitude),
            append(count_table$decimalLongitude, meas_table$decimalLongitude)
         ),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id)

```